export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Afghanistan": ["Kabul"],
  "Argentina": ["Buenos Aires"],
  "Australia": ["Adelaide", "Brisbane", "Melbourne", "Perth", "Sydney"],
  "Austria": ["Vienna"],
  "Bangladesh": ["Dhaka"],
  "Belgium": ["Brussels"],
  "Brazil": ["Brasilia", "Rio de Janeiro", "Sao Paulo"],
  "Canada": ["Calgary", "Edmonton", "Montreal", "Ottawa", "Toronto", "Vancouver"],
  "China": ["Beijing", "Chongqing", "Guangzhou", "Hong Kong", "Macau", "Shanghai", "Shenzhen"],
  "Colombia": ["Bogota"],
  "Egypt": ["Cairo"],
  "France": ["Marseille", "Paris"],
  "Germany": ["Berlin", "Frankfurt", "Hamburg", "Munich"],
  "Greece": ["Athens"],
  "India": ["Ahmedabad", "Bangalore", "Chennai", "Delhi", "Hyderabad", "Kolkata", "Mumbai", "New Delhi", "Pune"],
  "Indonesia": ["Jakarta"],
  "Ireland": ["Dublin"],
  "Israel": ["Jerusalem", "Tel Aviv"],
  "Italy": ["Milan", "Naples", "Rome"],
  "Japan": ["Fukuoka", "Osaka", "Tokyo"],
  "Kenya": ["Nairobi"],
  "Malaysia": ["Kuala Lumpur"],
  "Mexico": ["Guadalajara", "Mexico City", "Monterrey"],
  "Netherlands": ["Amsterdam"],
  "New Zealand": ["Auckland", "Wellington"],
  "Nigeria": ["Abuja", "Lagos"],
  "Pakistan": ["Islamabad", "Karachi", "Lahore"],
  "Philippines": ["Manila"],
  "Portugal": ["Lisbon"],
  "Russia": ["Moscow", "St. Petersburg"],
  "Saudi Arabia": ["Riyadh"],
  "Singapore": ["Singapore"],
  "South Africa": ["Cape Town", "Durban", "Johannesburg", "Pretoria"],
  "South Korea": ["Seoul"],
  "Spain": ["Barcelona", "Madrid"],
  "Sweden": ["Stockholm"],
  "Switzerland": ["Bern", "Geneva", "Zurich"],
  "Thailand": ["Bangkok"],
  "Turkey": ["Ankara", "Istanbul"],
  "United Arab Emirates": ["Abu Dhabi", "Dubai"],
  "United Kingdom": ["Belfast", "Edinburgh", "London"],
  "United States": ["Atlanta", "Austin", "Baltimore", "Boston", "Chicago", "Dallas", "Denver", "Honolulu", "Houston", "Las Vegas", "Los Angeles", "Miami", "Minneapolis", "New York", "Philadelphia", "Phoenix", "Portland", "San Antonio", "San Diego", "San Francisco", "San Jose", "Seattle", "Washington D.C."],
  "Vietnam": ["Hanoi", "Ho Chi Minh City"]
};

// Fallback for countries not explicitly listed above or when no country is selected
export const ALL_CITIES = Object.values(CITIES_BY_COUNTRY).flat().sort();
